# Generated by Django 5.2.15 on 2026-08-27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


MUTICA_INTEGRATION_ID = uuid.UUID("2ae13667-f4a6-45a0-b48b-7fb159193ff2")


def register_mutica_provider(apps, schema_editor):
    Integration = apps.get_model("db", "Integration")
    integration, created = Integration.objects.get_or_create(
        provider="mutica",
        defaults={
            "id": MUTICA_INTEGRATION_ID,
            "title": "Mutica",
            "network": 1,
            "description": {"text": "Delegate Plane work items to a connected Mutica environment."},
            "author": "Plane",
            "metadata": {"connection_type": "workspace"},
            "verified": True,
        },
    )
    if not created:
        integration.title = "Mutica"
        integration.description = {"text": "Delegate Plane work items to a connected Mutica environment."}
        integration.author = "Plane"
        integration.metadata = {"connection_type": "workspace"}
        integration.verified = True
        integration.save(update_fields=["title", "description", "author", "metadata", "verified"])


def unregister_mutica_provider(apps, schema_editor):
    Integration = apps.get_model("db", "Integration")
    WorkspaceIntegration = apps.get_model("db", "WorkspaceIntegration")
    if not WorkspaceIntegration.objects.filter(integration__provider="mutica").exists():
        Integration.objects.filter(provider="mutica").delete()


def audit_fields():
    return [
        ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
        ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
        ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
        (
            "id",
            models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        (
            "created_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        (
            "updated_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
    ]


class Migration(migrations.Migration):
    dependencies = [("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more")]

    operations = [
        migrations.CreateModel(
            name="MuticaConnection",
            fields=audit_fields()
            + [
                ("endpoint_url", models.URLField(max_length=2048)),
                ("signing_secret", models.TextField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace_integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutica_connection",
                        to="db.workspaceintegration",
                    ),
                ),
            ],
            options={"db_table": "mutica_connections", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="MuticaExternalAgent",
            fields=audit_fields()
            + [
                ("external_id", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("avatar_url", models.URLField(blank=True, max_length=2048, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "workspace_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutica_agents",
                        to="db.workspaceintegration",
                    ),
                ),
            ],
            options={"db_table": "mutica_external_agents", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="MuticaIssueDelegation",
            fields=audit_fields()
            + [
                ("correlation_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dispatching", "Dispatching"),
                            ("handed_off", "Handed off"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        default="dispatching",
                        max_length=32,
                    ),
                ),
                ("failure_category", models.CharField(blank=True, max_length=64)),
                ("handed_off_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations",
                        to="db.muticaexternalagent",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mutica_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutica_delegations",
                        to="db.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={"db_table": "mutica_issue_delegations", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="MuticaDeliveryAttempt",
            fields=audit_fields()
            + [
                ("delivery_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("retryable_failure", "Retryable failure"),
                            ("permanent_failure", "Permanent failure"),
                            ("stale", "Stale"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("failure_category", models.CharField(blank=True, max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="db.muticaissuedelegation",
                    ),
                ),
            ],
            options={"db_table": "mutica_delivery_attempts", "ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="muticaexternalagent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace_integration", "external_id"),
                name="mutica_agent_unique_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="muticaexternalagent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_default", True), ("is_enabled", True)),
                fields=("workspace_integration",),
                name="mutica_agent_one_enabled_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="muticaissuedelegation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["dispatching", "handed_off", "failed"])),
                fields=("issue",),
                name="mutica_delegation_one_active_per_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="muticadeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("delegation", "attempt_number"), name="mutica_delivery_unique_attempt_number"
            ),
        ),
        migrations.RunPython(register_mutica_provider, reverse_code=unregister_mutica_provider),
    ]
