# Generated by Django 4.2
# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("db", "0124_project_page_hierarchy"), ("license", "0007_storageprofile")]

    operations = [
        migrations.AddField(
            model_name="fileasset",
            name="storage_profile",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="license.storageprofile"),
        )
    ]
