# Generated by Django 4.2
# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("license", "0006_instance_is_current_version_deprecated")]

    operations = [
        migrations.CreateModel(
            name="StorageProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("provider", models.CharField(choices=[("ALIYUN_OSS", "Aliyun OSS"), ("S3", "Amazon S3")], default="ALIYUN_OSS", max_length=32)),
                ("bucket", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=128)),
                ("endpoint", models.URLField(blank=True, max_length=500)),
                ("access_key_id", models.CharField(max_length=255)),
                ("access_key_secret", models.TextField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("VERIFIED", "Verified"), ("ACTIVE", "Active"), ("RETIRED", "Retired")], default="DRAFT", max_length=16)),
                ("file_size_limit", models.PositiveBigIntegerField(default=104857600)),
                ("object_prefix", models.CharField(default="plane-assets/", max_length=255)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_error", models.TextField(blank=True, default="")),
                ("last_probe_at", models.DateTimeField(blank=True, null=True)),
                ("probe_object_key", models.CharField(blank=True, default="", max_length=800)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="storageprofile_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="storageprofile_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storage_profiles", to="license.instance")),
            ],
            options={"db_table": "instance_storage_profiles", "ordering": ("-created_at",)},
        ),
        migrations.AddIndex(model_name="storageprofile", index=models.Index(fields=["instance", "status"], name="storage_profile_status_idx")),
    ]
